#!/bin/bash

# NAME
#    check-links - compare links in translated and original strings of POs

# SYNOPSIS
#       check-links PO_FILE [-g GUI_EDITOR]
#       or
#       check-links -l LANG [-g GUI_EDITOR]

# DESCRIPTION
#    check-links processes either one PO, or all the POs is the working
#    directory. It selects all the links (including anchors and email
#    addresses), and shows differences between the original document and its
#    translation.

#    Method:
#    * remove comments;
#    * unwrap messages;
#    * remove footer strings that contain localized or customized links.
#    * process msgid and msgstr together:
#      - isolate links (after href=", and before the following double-quote);
#      - remove what is specific to msgstr, such as #TransNote*, #sommaire,
#        *-rev, etc. (this can be commented out);
#      - save the link collections for msgid and msgstr separately, along
#        with string numbers and fuzzy tags.
#    * make a diff and display it.

# OPTIONS AND CURRENT SETTINGS
#    Displayed by:   check-links -h
#
#    Configuration file:
#    The command-line parameters can be set once and for all in a configuration
#    file (also used by transvalid-batch, www-commit, micro-www-checkout, and
#    cvs-sync), with the syntax:
#       parameter1="value1"
#       parameter2="value2"
#    This configuration overrides the default settings but is superseded by the
#    command line. The file ($conf) is specified under "Parameters".

#==============================================================================

set -e
set -o pipefail

function version () {
cat <<EOF
${0##*\/} version 0.2
Copyright (C) 2013 Denis Barbier
              2013, 2016 Thérèse Godefroy
You may redistribute this script and/or modify it under the terms of the
Creative Commons CC0 license
EOF
}

function usage () {
cat <<EOF

Usage: check-links PO_FILE [-g GUI_EDITOR]
       or
       check-links -l LANG [-g GUI_EDITOR]

  The script processes either one PO, or all the POs is the working directory.
  It selects all the links (including anchors and email addresses), and shows
  differences between the original document and its translation.

Options:
  -l LANG               [$lang]
      Specify the language code if no PO file is specified.

  -g GUI_EDITOR         [$geditor]
      Specify a GUI editor, preferably with syntax highlighting (optional).

  -V  Display version info and exit
  -h  Display this help and exit

  The parameter values can be set in a configuration file:
       $conf
  One line per parameter, with syntax: param='VALUE'
  The command line overrides those settings.
  The language code can also be entered at the prompt.

Report bugs to <godef.th@free.fr>

EOF
}

## Parameters

conf="$HOME/.profile"
geditor=""
lang=""

test -s "$conf" && source $conf

# Parse the command line.
OPTIND=1
while getopts "h?Vl:g:" opt; do
  case "$opt" in
     h | \? ) usage; exit 0 ;;
     V ) version; exit 0 ;;
     l ) lang=$OPTARG ;;
     g ) editor=$OPTARG ;;
  esac
done
shift $((OPTIND-1))
[ "$1" = "--" ] && shift


function isolate_links () {
  awk '
    BEGIN {
      RS = "\n\n"
      FS = "\n"
      OFS= "\t"
    }
    {
      gsub ( /^#.*\n#, fuzzy.*\nmsgid/ , "Fmsgid" )
      gsub ( /^#.*\nmsgid/ , "msgid" )
      gsub ( /"\n"/ , "" )
      gsub ( /\\"/ , "\"" )
      gsub ( /[ \t]*/ , "" )
      if ( FNR == 1 )
      {
        print "\n=================================================\n" > "href-id"
        print "\n""*** " FILENAME \
              "\n-------------------------------------------------\n" > "href-str"
      }
      if ( !/^#/ &&
           !/GNUN-SLOT:/ &&
           !/msgid"Pleaseseethe<ahref="\/server\/standards\/README/ &&
           !/msgid"Thispageislicensed.*\/licenses\/by-nd\/3.0\/us/  &&
           !/msgid"Thispageislicensed.*\/licenses\/by-nd\/4.0\// )
      {
        gsub ( /href="#TransNote[^"]+"/ , "" )  # ) 
        gsub ( /href="[^"]+-rev"/ , "" )        # )
        gsub ( /href="#TOC[^"]*"/ , "" )        # ) Remove
        gsub ( /href="#tm"/ , "" )              # ) translation-specific
        gsub ( /href="#t[0-9]{4}"/ , "" )       # ) anchors.
        gsub ( /href="#sommaire"/ , "" )        # )
        gsub ( /href="[^"]*/ , "& " )  # Mark the ends of URLs.
        gsub ( /^[^ ]+$/ , "" )        # Remove strings with no URL anywhere.
        gsub ( / [^ ]+$/ , "" )        # Strip end of msgstr or complete msgstr if no URL.
        gsub ( /msg(id|str)/ , " &" )  # Mark beginning of msg(id|str).
        gsub ( / [^ ]+\n / , "\n " )   # Strip end of msgid or complete msgid if no URL.
        gsub ( /^F\n / , "" )
        gsub ( / [^ ]+href="/ , " " )  # Strip beginning of msg* & between URLs.
        sub  ( / / , "*" , $1 ) ; sub ( / / , "*" , $2 )
        gsub ( / / , "\n\t\t" , $1 ) ; gsub ( / / , "\n\t\t" , $2 )
        sub  ( /*/ , "\t" , $1 ) ; gsub ( /*/ , "\t" , $2 )
        print FNR-1 , $1 > "href-id"; print FNR-1 , $2 > "href-str"
      }
    }
    END {
      print "\n=================================================\n" > "href-id"
      print "\n" > "href-str"
    }' $(<list)
}

#====================
echo "${0##*\/} - compare links in translated and original strings of POs"

## Input

# Single PO
po=$1
po=${po#\'}; po=${po%\'}
if  test -s "$po" -a  "${po%.po}" != "$po"; then
  echo $po > list

# or whole directory
else
  if test -z "$lang"; then
    echo "*** Please enter a language code, or hit Enter to quit."
    read lang
    test -z "$lang" && exit 0
  fi

  # List POs for the specified language in the working directory,
  # skipping includes and sitemap.
  find * -name "*.$lang.po" | sort |
  awk '{ if (!/planetfeeds/      && !/compendia/  && !/sitemap/      &&
             !/-include-(1|2)\./ && !/-menu\./    && !/footer-text/  &&
             !/bottom-notes/     && !/outdated\./ && !/top-addendum/ &&
             !/fs-gang/)
         { print }
       }' > list
fi


## Isolate and compare links.

if test -s list; then
  isolate_links
  diff -U1 href-id href-str > href.diff || true
  if test $(which "$geditor"); then
    $geditor href.diff &
  else
    echo -e "\n*** The diff file is href.diff."
  fi
else
  echo 1>&2 "!!! No PO to work on."
  sleep 5
  exit 1
fi

rm -f list href-id href-str
exit 0
