#!/bin/bash

# NAME
#    check-links - compare links in translated and original strings of POs

# SYNOPSIS
#    check-links -t /.../www-TEAM

# DESCRIPTION
#    check-links processes all the POs in the team directory (except includes,
#    planetfeeds, compendia and sitemap) to detect relevant differences
#    between translated and original links, including anchors and mailing
#    addresses.
#
#    Method:
#    * remove comments;
#    * turn the messages into single lines, even if they contain \n (msgcat
#      cannot be used because it splits after \n);
#    * select all lines that contain links, according to whether they start
#      with msgid or msgstr, then treat each series separately:
#      - add a line break after each occurrence of "href=" (after removing any
#        trailing space), to have each link at the beginning of a line;
#      - list the links;
#    * process the lists to remove links that are specific to msgstr, such as
#      #TransNote*, #sommaire, -rev (also in msgid in stallman-mec-india),
#      etc.;
#    * make a diff;
#    * prune differences that are only found in footer strings. This part
#      should be customized for each team (team's mailing address, etc.)
#    * The resulting file is ../href.diff.

#    Awk background:
#    http://oreilly.com/catalog/unixnut3/chapter/ch11.html
#    http://backreference.org/2010/02/10/idiomatic-awk/

# OPTIONS
#    Displayed by:   check-links -h
#
#    Configuration file:
#    The command-line parameters can be set once and for all in a configuration
#    file (also used by transvalid-batch, cvs-sync, www-commit, and
#    micro-www-checkout), with the syntax:
#       parameter1="value1"
#       parameter2="value2"
#    This configuration overrides the default settings but is superseded by the
#    command line. The file ($conf) is specified under "Parameters".

#==============================================================================

set -e
set -o pipefail

function version () {
cat <<EOF
${0##*\/} version 0.1
Copyright (C) 2013 Denis Barbier, Thérèse Godefroy
You may redistribute this script and/or modify it under the terms of the
Creative Commons CC0 license
EOF
}

function usage () {
cat <<EOF

Usage: check-links -t /.../www-TEAM

  The script processes all the POs in the team directory. It detects
  relevant differences between the links in original strings and those
  in the corresponding translated strings, and displays them.

Options:

  -t /.../www-TEAM         [$teamdir]
      Specify the absolute path to the team directory (required)
  -V  Display version info and exit
  -h  Display this help and exit

  The parameter values can be set in a configuration file:
       $conf
  One line per parameter, with syntax: param='VALUE'

Report bugs to <godef.th@free.fr>
EOF
}

echo "${0##*\/} - compare links in translated and original strings of POs"


## Parameters

conf="$HOME/.profile"
teamdir=""
test -s "$conf" && source $conf

# Parse the command line.
OPTIND=1
while getopts "h?Vt:" opt; do
  case "$opt" in
     h | \? ) usage; exit 0 ;;
     V ) version; exit 0 ;;
     t ) teamdir=$OPTARG ;;
  esac
done
shift $((OPTIND-1))
[ "$1" = "--" ] && shift


## Compare links.

f_tmp=$(mktemp -t cklk.XXXXXX)       || exit 1
href_msgstr=$(mktemp -t cklk.XXXXXX) || exit 1
href_msgid=$(mktemp -t cklk.XXXXXX)  || exit 1
trap 'rm -f "$f_tmp" "$href_msgstr" "$href_msgid"' EXIT

cd $teamdir

echo "==============================" > ../href.diff
for f in $(find * -name \*.fr.po | sort); do
  if [[ ! "$f" =~ 'planetfeeds' ]] \
  && [[ ! "$f" =~ "compendia/" ]] \
  && [[ ! "$f" =~ "sitemap" ]] \
  && [[ ! "$f" =~ "head-include-2" ]] \
  && [[ ! "$f" =~ "philosophy-menu" ]] \
  && [[ ! "$f" =~ "education-menu" ]] \
  && [[ ! "$f" =~ "body-include" ]] \
  && [[ ! "$f" =~ "footer-text" ]] \
  && [[ ! "$f" =~ "bottom-notes" ]] \
  && [[ ! "$f" =~ "outdated" ]] \
  && [[ ! "$f" =~ "top-addendum" ]]; then
    echo $f >> ../href.diff
    awk '!/^#/
      $1=$1 {ORS=" "}' $f |
    sed -e 's," ",,g' \
        -e 's,msg,\nmsg,g' > $f_tmp
    grep '^msgstr.*href=' $f_tmp |
    sed -e 's,href= \\",href=\\",g' \
        -e 's,href=,href=\n,g' |
    sed -e 's,\\"\([^\\]*\).*,\1,' \
        -e 's,&quot;\([^&]*\).*,\1,' |
    awk '!/msgstr/ \
      && !/#TransNote/ \
      && !/#sommaire/ \
      && !/#t[0-9]{4}/ \
      && !/-rev$/ \
      && !/#tm$/ \
      && !/#TOC$/' > $href_msgstr
    grep '^msgid.*href=' $f_tmp |
    sed -e 's,href= \\",href=\\",g' \
        -e 's,href=,href=\n,g' |
    sed -e 's,\\"\([^\\]*\).*,\1,' \
        -e 's,&quot;\([^&]*\).*,\1,' |
    awk '!/msgid/ \
         !/-rev$/' > $href_msgid
    diff -U2 -I 'mailto:web-translators' \
             -I 'mailto:trad-gnu&#64;april.org' \
             -I 'mailto:trad-gnu@april.org' \
             -I 'http://creativecommons.org/licenses' \
             -I 'https://creativecommons.org/licenses' \
             -I '/server/standards/README.translations.html' \
    $href_msgid $href_msgstr >> ../href.diff || true
    echo "==============================" >> ../href.diff
  fi
done

less ../href.diff
exit 0
