#!/bin/bash

# Copyright (C) 2008 Free Software Foundation, Inc.

# This file is part of GNUnited Nations.

# GNUnited Nations is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# GNUnited Nations is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with GNUnited Nations.  If not, see <http://www.gnu.org/licenses/>.

# Usage:
#
# ./validate-html-notify [--dry-run] RCPT FILE
#
# Example:
#
# ./validate-html-notify kaloian@doganov.org article.html

function usage() {
    echo 1>&2 Usage: ./validate-html-notify [--dry-run] RCPT FILE
    exit 1
}

[ $# -gt 0 ] || usage

# Read arguments
DRY_RUN=""
if [ "$1" == "--dry-run" ]; then
    [ $# -eq 3 ] || usage
    DRY_RUN="$1"
    RCPT="$2"
    FILE="$3"
    shift 3
else
    [ $# -eq 2 ] || usage
    RCPT="$1"
    FILE="$2"
    shift 2
fi

SUBJ="[GNUN Error] ${FILE#../../} is not valid XHTML"

./mailfail $DRY_RUN "$RCPT" "$SUBJ" ./validate-html "$FILE"
